### ISSUE TITLE
`test_tree.nim` failing for Nim v2.0.2 in PR branch `ipa-tree-types` and the `develop` branch as well

### ISSUE THREAD

**Issue by agnxsh** [status-im/nim-eth-verkle#21]
<img width="681" alt="image" src="https://github.com/status-im/nim-eth-verkle/assets/80243668/816eabe0-e9cf-4be9-a194-f45e0f19e5ee">

Found the same for `develop` branch as well

**Comment by agnxsh** [comment]
Strangely it does work with Nim v1.6.16 and v1.6.18

<img width="682" alt="image" src="https://github.com/status-im/nim-eth-verkle/assets/80243668/0afbb4e5-a518-4c0e-92a6-64d72634ac3a">

**Comment by advaita-saha** [comment]
seems like the error is resulting from the typecasting in line 212, `node.BranchesNode`

**Comment by tersec** [comment]
Tried all 2x2x2=8 combinations of:
- Nim 2.0.2 and 2.0.10:
```
Nim Compiler Version 2.0.10 [Linux: amd64]
Compiled at 2024-07-30
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 92e505577e8b6b9214b6fcdd7fe1b0e9a244023b
active boot switches: -d:release
```
and
```
Nim Compiler Version 2.0.2 [Linux: amd64]
Compiled at 2024-07-31
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c4c44d10df8a14204a75c34e499def200589cb7c
active boot switches: -d:release
```

- Commit `4cb17a3d056fcac03142ce08e05fb616977efd09` on `develop`  and `6db26394a6f9c2ba6d88ccc6f1750325d42502f8` on `ipa-tree-types`

and `--mm:orc` and `--mm:refc`.

Can reproduce this on both commits but only with 2.0.2 with `--mm:orc`, not `--mm:refc`.

Since 2.0.10 (current `version-2-0`, soon to be released version) doesn't seem to exhibit this, this seems to have been fixed upstream by Nim, whatever was happening.

In general, the reason one sometimes sees this jump from 1.6 to 2.0 when not specifying `--mm:orc` or `--mm:refc` explicitly is that aside from everything else, Nim 2.0 switched the default from `--m:refc` to `--mm:orc`, so by default ORC issues start appearing even if they had been there the whole time and would have been reproducible in 1.6 with `--mm:orc` too, just, no one had tried (and there's not much reason to).
